In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt


dataset = load_dataset("lukebarousse/data_jobs")
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Generating train split: 100%|██████████| 785741/785741 [00:02<00:00, 273566.69 examples/s]

In [2]:
df.iloc[0]

job_title_short                                       Senior Data Engineer
job_title                Senior Clinical Data Engineer / Principal Clin...
job_location                                                 Watertown, CT
job_via                                                    via Work Nearby
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                       Texas, United States
job_posted_date                                        2023-06-16 13:44:15
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                  United States
salary_rate                                                            NaN
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                                          Boehringer Ingelheim
job_skills                                                             NaN
job_type_skills                                                        NaN
Name: 0, dtype: object

In [5]:
df.iloc[0:11, 0:3]

         job_title_short  ...                  job_location
0   Senior Data Engineer  ...                 Watertown, CT
1           Data Analyst  ...  Guadalajara, Jalisco, Mexico
2          Data Engineer  ...               Berlin, Germany
3          Data Engineer  ...               San Antonio, TX
4          Data Engineer  ...                Washington, DC
5          Data Engineer  ...                      Anywhere
6   Senior Data Engineer  ...                  Dearborn, MI
7          Data Engineer  ...                      Anywhere
8       Business Analyst  ...           Copenhagen, Denmark
9         Data Scientist  ...                      Anywhere
10         Data Engineer  ...            Basel, Switzerland

[11 rows x 3 columns]

In [6]:
df

             job_title_short  ...                                    job_type_skills
0       Senior Data Engineer  ...                                                NaN
1               Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2              Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3              Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4              Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
...                      ...  ...                                                ...
785736     Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737          Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738      Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739         Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740     Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[785741 rows x 17 columns]

In [7]:
df.loc[0:11, 'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN
11         NaN              NaN              NaN

In [11]:
#drop the salary_rate that has NaN values
df.loc[:, 'salary_rate':'salary_hour_avg'].dropna(subset='salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]

In [12]:
df_cleaned = df.dropna(how='all')
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [13]:
df_cleaned.iloc[:10,11:14]

  salary_rate  salary_year_avg  salary_hour_avg
0         NaN              NaN              NaN
1         NaN              NaN              NaN
2         NaN              NaN              NaN
3         NaN              NaN              NaN
4         NaN              NaN              NaN
5         NaN              NaN              NaN
6         NaN              NaN              NaN
7         NaN              NaN              NaN
8         NaN              NaN              NaN
9         NaN              NaN              NaN